---
title: "Investigating how tolerant symbiont parameters affect rescue"
author: "Ross Cunning and Alexandra Brown"
date: "5/6/2020"
output: html_document
---

```{r}
#Set kintr options
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, fig.width=8, fig.height=8)

library(coRal)
library(foreach)
library(parallel)
library(doParallel)
library(plot.matrix)
library("RColorBrewer")
library("viridis")
library("factoextra")
library("e1071")
library("coda")
library("rstan")
options(mc.cores = 8)
library("bayesplot")
library("ggplot2")
library("gridExtra")
options(repr.plot.res=240)
```
## A function for detecting when the host growth rate changes sign

```{r, cache = TRUE}
detect_gr_change <- function(run) {
    prevGr <- run$dH.Hdt[1:length(run$dH.Hdt)-1]
    currGr <- run$dH.Hdt[2:length(run$dH.Hdt)]
    changelist <- ((run$time[2:length(run$time)] + run$time[1:length(run$time)-1])/2)[prevGr*currGr<= 0]
    if (length(changelist) > 0) {
          return(changelist[length(changelist)])
   }
   return(NA)
}
```

```{r, cache = TRUE}
# one-symbiont parameters
pars1 <- def_pars(nsym=1)
pars1$initS <- 1e-4

# run simulations for 3000 days
time<-seq(1, 3000, 0.1)

# draw sets of parameter values randomly
# hopefully this will speed things up compared to looking over a grid

draws = 10000; # number of sets of random parameter combinations to look over

search_params <- data.frame(
                            # Environmental parameters
                            "L" = runif(draws, 0, 40),       # Light, choose values between 0 and 40
                            "N" = runif(draws, 0, 4e-6),     # DIN, choose values between 0 and 4e-6
                            "X" = runif(draws, 0, 4e-7),     # Food, choose values between 0 and 4e-7
                            # Host parameter
                            "kCO2" = runif(draws, 10, 50),   # Host carbon concentrating, choose values between 10 and 50
                            # Tolerant symbiont parameters
                            "kNPQ" = runif(draws, 112, 224), # Non-photochemical quenching, choose values between 112 and 124
                            "astar" = runif(draws, 0.67, 1.34), # astar, choose values between 0.7 and 1.34     
                            "jSGm" = runif(draws, 0.15, 0.25), # Maximum growth rate, choose values between 0.15 and 0.25
                            "jCPm" = runif(draws, 1, 2.8), # Maximum photosynthetic rate, choose values between 1 and 2.8
                            "kROS" = runif(draws, 80, 250), # kROS, choose values between 80 and 250
                            "b" = runif(draws, 1, 5))   # b, choose values between 1 and 5

# set up for parallel run
cl <- makeCluster(detectCores() - 1)
registerDoParallel(cl)

# start the timer
start <- proc.time()


# results will hold the parameter values tested as well as whether the tolerant symbiont "rescued"
# the sensitive symbiont at each parameter value

results <- foreach(i=1:nrow(search_params), .combine='rbind', .packages='dplyr') %dopar% {

    # Set up the environmental conditions
    env <- coRal::init_env(time=time, L=c(search_params[i, "L"], search_params[i, "L"], 0),
                           N=c(search_params[i, "N"], search_params[i, "N"], 0), X=c(search_params[i, "X"], search_params[i, "X"], 0))

    # simulate dynamics with just the sensitive symbiont
    run_1symb <- coRal::run_coral(time=time, env=env, pars=replace(pars1, "kCO2", search_params[i, "kCO2"]))

    # initialize rescue; will be TRUE if the tolerant symbiont rescued the sensitive
    rescue <- FALSE

    # initialize reason; will give the reason for lack of rescue if rescue does not occur
    # reason = "S_lives" -> host recovers with sensitive symbiont alone; does not need to be rescued by tolerant
    # reason = "T_dies" -> tolerant symbiont unable to rescue host
    # reason = "T_dominates" -> tolerant symbiont permits host recovery while sensitive does not, but tolerant dominates post-recovery
    # reason = "rescue" -> rescue occurred
    reason <- "S_lives"

    # if the coral can achieve positive growth with just the sensitive symbiont, the sensitive symbiont doesn't need to be rescued
    # only investigate the two-symbiont case if host growth is negative or 0 at the end of the simulation
    rescue_time <- NA

    if (run_1symb$dH.Hdt[length(run_1symb$dH.Hdt)] <= 0) {

         # two-symbiont parameters
         pars2 <- coRal::def_pars(nsym=2)
         pars2$kCO2 <- search_params[i, "kCO2"]
         pars2$initS[1:2] <- c(0.5e-4, 0.5e-4)
         pars2$astar[2] <- search_params[i, "astar"]
         pars2$kNPQ[2] <- search_params[i, "kNPQ"]
         pars2$jSGm[2] <- search_params[i, "jSGm"]
         pars2$jCPm[2] <- search_params[i, "jCPm"]
         pars2$kROS[2] <- search_params[i, "kROS"]
         pars2$b[2] <- search_params[i, "b"]



        run_2symb <- coRal::run_coral(time=time, env=env, pars=pars2)

        # if the coral didn't achieve positive growth with both symbionts, then rescue definitely didn't happen
        # set reason to "T_dies" in case this is the case (we'll change it later if it isn't)
        reason <- "T_dies"

        # if the tolerant symbiont rescues the sensitive symbiont, we want to record how long that takes to happen
        # if that doesn't happen, we'll record the time to rescue as NA


        # only further investigate the case where host growth is positive at the end of the simulation

        if (run_2symb$dH.Hdt[length(run_2symb$dH.Hdt)] > 0) {

            # the sensitive symbiont (S1) has been rescued if it now has higher biomass than the tolerant symbiont (S2)
            # set reason to "T_dominates" for now because this is what must have happened if rescue did not occur
            reason <- "T_dominates"

            if (run_2symb$S.1[length(run_2symb$S.1)] > run_2symb$S.2[length(run_2symb$S.2)]) {

                rescue <- TRUE
                reason <- "rescue"

                rescue_time <- detect_gr_change(run_2symb)
            }
        }
    }

    # return the parameters and whether rescue was successful or not
    list("L"=search_params[i, "L"], "N"=search_params[i, "N"],
    "X"=search_params[i, "X"], "kCO2"=search_params[i, "kCO2"],
    "astar"=search_params[i, "astar"], "kNPQ"=search_params[i, "kNPQ"],
    "jSGm"=search_params[i, "jSGm"], "jCPm"=search_params[i, "jCPm"],
    "kROS"=search_params[i, "kROS"], "b"=search_params[i, "b"],
    "rescue"=rescue, "reason"=reason, "rescue_time"=rescue_time)
}

stopCluster(cl) # stop the cluster

# print time this took
print("Simulation took")
print(proc.time() - start)

# store results in dataframe
rescue_tol_param <- data.frame(results, row.names=NULL)

```

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs astar", xlab="astar", ylab="L", xlim=c(0.67, 1.34), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs kNPQ", xlab="kNPQ", ylab="L", xlim=c(112, 224), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jSGm", xlab="jSGm", ylab="L", xlim=c(0.15, 0.25), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jCPm", xlab="jCPm", ylab="L", xlim=c(1, 2.8), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs kROS", xlab="kROS", ylab="L", xlim=c(80, 250), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs b", xlab="b", ylab="L", xlim=c(1, 5), ylim=c(0, 40))

```

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs astar", xlab="astar", ylab="DIN", xlim=c(0.67, 1.34), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs kNPQ", xlab="kNPQ", ylab="DIN", xlim=c(112, 224), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jSGm", xlab="jSGm", ylab="DIN", xlim=c(0.15, 0.25), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jCPm", xlab="jCPm", ylab="DIN", xlim=c(1, 2.8), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs kROS", xlab="kROS", ylab="DIN", xlim=c(80, 250), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs b", xlab="b", ylab="DIN", xlim=c(1, 5), ylim=c(0, 4e-6))

```

```{r}
par(mfrow=c(4, 4), pty="s")

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="kNPQ vs astar", xlab="astar", ylab="kNPQ", xlim=c(0.67, 1.34), ylim=c(112, 224))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jSGm vs astar", xlab="astar", ylab="jSGm", xlim=c(0.67, 1.34), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs astar", xlab="astar", ylab="jCPm", xlim=c(0.67, 1.34), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs astar", xlab="astar", ylab="kROS", xlim=c(0.67, 1.34), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"astar"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs b", xlab="astar", ylab="b", xlim=c(0.67, 1.34), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="jSGm vs kNPQ", xlab="kNPQ", ylab="jSGm", xlim=c(112, 224), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs kNPQ", xlab="kNPQ", ylab="jCPm", xlim=c(112, 224), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs kNPQ", xlab="kNPQ", ylab="kROS", xlim=c(112, 224), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kNPQ"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kNPQ", xlab="kNPQ", ylab="b", xlim=c(112, 224), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs jSGm", xlab="jSGm", ylab="jCPm", xlim=c(0.15, 0.25), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jSGm", xlab="jSGm", ylab="kROS", xlim=c(0.15, 0.25), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jSGm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jSGm", xlab="jSGm", ylab="b", xlim=c(0.15, 0.25), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jCPm", xlab="jCPm", ylab="kROS", xlim=c(1, 2.8), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"jCPm"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jCPm", xlab="jCPm", ylab="b", xlim=c(1, 2.8), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$rescue==TRUE,"kROS"], rescue_tol_param[rescue_tol_param$rescue==TRUE,"b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kROS", xlab="kROS", ylab="b", xlim=c(80, 250), ylim=c(1, 5))

```

# S lives

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs astar", xlab="astar", ylab="L", xlim=c(0.67, 1.34), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs kNPQ", xlab="kNPQ", ylab="L", xlim=c(112, 224), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jSGm", xlab="jSGm", ylab="L", xlim=c(0.15, 0.25), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jCPm", xlab="jCPm", ylab="L", xlim=c(1, 2.8), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs kROS", xlab="kROS", ylab="L", xlim=c(80, 250), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], rescue_tol_param[rescue_tol_param$reason=="S_lives","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs b", xlab="b", ylab="L", xlim=c(1, 5), ylim=c(0, 40))

```

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs astar", xlab="astar", ylab="DIN", xlim=c(0.67, 1.34), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs kNPQ", xlab="kNPQ", ylab="DIN", xlim=c(112, 224), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jSGm", xlab="jSGm", ylab="DIN", xlim=c(0.15, 0.25), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jCPm", xlab="jCPm", ylab="DIN", xlim=c(1, 2.8), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs kROS", xlab="kROS", ylab="DIN", xlim=c(80, 250), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], rescue_tol_param[rescue_tol_param$reason=="S_lives","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs b", xlab="b", ylab="DIN", xlim=c(1, 5), ylim=c(0, 4e-6))

```

```{r}
par(mfrow=c(4, 4), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="kNPQ vs astar", xlab="astar", ylab="kNPQ", xlim=c(0.67, 1.34), ylim=c(112, 224))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jSGm vs astar", xlab="astar", ylab="jSGm", xlim=c(0.67, 1.34), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs astar", xlab="astar", ylab="jCPm", xlim=c(0.67, 1.34), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs astar", xlab="astar", ylab="kROS", xlim=c(0.67, 1.34), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","astar"], rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs b", xlab="astar", ylab="b", xlim=c(0.67, 1.34), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="jSGm vs kNPQ", xlab="kNPQ", ylab="jSGm", xlim=c(112, 224), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs kNPQ", xlab="kNPQ", ylab="jCPm", xlim=c(112, 224), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs kNPQ", xlab="kNPQ", ylab="kROS", xlim=c(112, 224), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kNPQ", xlab="kNPQ", ylab="b", xlim=c(112, 224), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs jSGm", xlab="jSGm", ylab="jCPm", xlim=c(0.15, 0.25), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jSGm", xlab="jSGm", ylab="kROS", xlim=c(0.15, 0.25), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jSGm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jSGm", xlab="jSGm", ylab="b", xlim=c(0.15, 0.25), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jCPm", xlab="jCPm", ylab="kROS", xlim=c(1, 2.8), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","jCPm"], rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jCPm", xlab="jCPm", ylab="b", xlim=c(1, 2.8), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="S_lives","kROS"], rescue_tol_param[rescue_tol_param$reason=="S_lives","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kROS", xlab="kROS", ylab="b", xlim=c(80, 250), ylim=c(1, 5))

```

# T dies

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs astar", xlab="astar", ylab="L", xlim=c(0.67, 1.34), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs kNPQ", xlab="kNPQ", ylab="L", xlim=c(112, 224), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jSGm", xlab="jSGm", ylab="L", xlim=c(0.15, 0.25), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jCPm", xlab="jCPm", ylab="L", xlim=c(1, 2.8), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs kROS", xlab="kROS", ylab="L", xlim=c(80, 250), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], rescue_tol_param[rescue_tol_param$reason=="T_dies","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs b", xlab="b", ylab="L", xlim=c(1, 5), ylim=c(0, 40))

```

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs astar", xlab="astar", ylab="DIN", xlim=c(0.67, 1.34), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs kNPQ", xlab="kNPQ", ylab="DIN", xlim=c(112, 224), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jSGm", xlab="jSGm", ylab="DIN", xlim=c(0.15, 0.25), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jCPm", xlab="jCPm", ylab="DIN", xlim=c(1, 2.8), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs kROS", xlab="kROS", ylab="DIN", xlim=c(80, 250), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], rescue_tol_param[rescue_tol_param$reason=="T_dies","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs b", xlab="b", ylab="DIN", xlim=c(1, 5), ylim=c(0, 4e-6))

```

```{r}
par(mfrow=c(4, 4), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="kNPQ vs astar", xlab="astar", ylab="kNPQ", xlim=c(0.67, 1.34), ylim=c(112, 224))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jSGm vs astar", xlab="astar", ylab="jSGm", xlim=c(0.67, 1.34), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs astar", xlab="astar", ylab="jCPm", xlim=c(0.67, 1.34), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs astar", xlab="astar", ylab="kROS", xlim=c(0.67, 1.34), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs b", xlab="astar", ylab="b", xlim=c(0.67, 1.34), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="jSGm vs kNPQ", xlab="kNPQ", ylab="jSGm", xlim=c(112, 224), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs kNPQ", xlab="kNPQ", ylab="jCPm", xlim=c(112, 224), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs kNPQ", xlab="kNPQ", ylab="kROS", xlim=c(112, 224), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kNPQ", xlab="kNPQ", ylab="b", xlim=c(112, 224), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs jSGm", xlab="jSGm", ylab="jCPm", xlim=c(0.15, 0.25), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jSGm", xlab="jSGm", ylab="kROS", xlim=c(0.15, 0.25), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jSGm", xlab="jSGm", ylab="b", xlim=c(0.15, 0.25), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jCPm", xlab="jCPm", ylab="kROS", xlim=c(1, 2.8), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jCPm", xlab="jCPm", ylab="b", xlim=c(1, 2.8), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dies","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dies","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kROS", xlab="kROS", ylab="b", xlim=c(80, 250), ylim=c(1, 5))

```

# T dominates

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs astar", xlab="astar", ylab="L", xlim=c(0.67, 1.34), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Light vs kNPQ", xlab="kNPQ", ylab="L", xlim=c(112, 224), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jSGm", xlab="jSGm", ylab="L", xlim=c(0.15, 0.25), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs jCPm", xlab="jCPm", ylab="L", xlim=c(1, 2.8), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs kROS", xlab="kROS", ylab="L", xlim=c(80, 250), ylim=c(0, 40))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","L"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Light vs b", xlab="b", ylab="L", xlim=c(1, 5), ylim=c(0, 40))

```

```{r}
par(mfrow=c(2, 3), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs astar", xlab="astar", ylab="DIN", xlim=c(0.67, 1.34), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="Nitrogen vs kNPQ", xlab="kNPQ", ylab="DIN", xlim=c(112, 224), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jSGm", xlab="jSGm", ylab="DIN", xlim=c(0.15, 0.25), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs jCPm", xlab="jCPm", ylab="DIN", xlim=c(1, 2.8), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs kROS", xlab="kROS", ylab="DIN", xlim=c(80, 250), ylim=c(0, 4e-6))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","N"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="Nitrogen vs b", xlab="b", ylab="DIN", xlim=c(1, 5), ylim=c(0, 4e-6))

```

```{r}
par(mfrow=c(4, 4), pty="s")

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="kNPQ vs astar", xlab="astar", ylab="kNPQ", xlim=c(0.67, 1.34), ylim=c(112, 224))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jSGm vs astar", xlab="astar", ylab="jSGm", xlim=c(0.67, 1.34), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs astar", xlab="astar", ylab="jCPm", xlim=c(0.67, 1.34), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs astar", xlab="astar", ylab="kROS", xlim=c(0.67, 1.34), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","astar"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs b", xlab="astar", ylab="b", xlim=c(0.67, 1.34), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
     main="jSGm vs kNPQ", xlab="kNPQ", ylab="jSGm", xlim=c(112, 224), ylim=c(0.15, 0.25))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs kNPQ", xlab="kNPQ", ylab="jCPm", xlim=c(112, 224), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs kNPQ", xlab="kNPQ", ylab="kROS", xlim=c(112, 224), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kNPQ"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kNPQ", xlab="kNPQ", ylab="b", xlim=c(112, 224), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="jCPm vs jSGm", xlab="jSGm", ylab="jCPm", xlim=c(0.15, 0.25), ylim=c(1, 2.8))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jSGm", xlab="jSGm", ylab="kROS", xlim=c(0.15, 0.25), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jSGm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jSGm", xlab="jSGm", ylab="b", xlim=c(0.15, 0.25), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="kROS vs jCPm", xlab="jCPm", ylab="kROS", xlim=c(1, 2.8), ylim=c(80, 250))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","jCPm"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs jCPm", xlab="jCPm", ylab="b", xlim=c(1, 2.8), ylim=c(1, 5))

plot(rescue_tol_param[rescue_tol_param$reason=="T_dominates","kROS"], rescue_tol_param[rescue_tol_param$reason=="T_dominates","b"], pch=19, col=rgb(0, 0, 1, alpha=0.1),
      main="b vs kROS", xlab="kROS", ylab="b", xlim=c(80, 250), ylim=c(1, 5))

```

```{r, cache=TRUE}
results_stan <- lapply(rescue_tol_param$reason,
      function(r) {
            if(r=="S_lives") {
                  1
            } else if (r=="rescue") {
                  2
            } else if (r=="T_dies") {
                  3
            } else if (r=="T_dominates") {
                  4
            } else {
                  NA
            }})

results_stan <- as.numeric(results_stan)

predictors_stan <- with(rescue_tol_param, {data.frame(L=as.numeric(L), N=as.numeric(N), X=as.numeric(X), kCO2=as.numeric(kCO2),
      astar=as.numeric(astar), kNPQ=as.numeric(kNPQ), jSGm=as.numeric(jSGm), jCPm=as.numeric(jCPm),
      kROS=as.numeric(kROS), b=as.numeric(b))})

predictors_stan <- as.matrix(predictors_stan)

ml_stan <- stan("multilogit.stan", data=list("K"=4, # number of outcomes (S_lives = 1, Rescue =2, T_dies=3, T_dominates=4)
                                  "N"=length(results_stan), # number of data points
                                  "D"=ncol(predictors_stan), # number of predictors (variables we changed)
                                  "y"=results_stan, # vector of observed outcomes
                                  "x"=predictors_stan), # matrix of observations and predictors
                      chains=8, iter=2000, cores=8)
```

```{r}
print(ml_stan)

slives_stan <- as.matrix(ml_stan, pars = list("beta[1,1]", "beta[2,1]", "beta[3,1]", "beta[4,1]", "beta[5,1]",
      "beta[6,1]", "beta[7,1]", "beta[8,1]", "beta[9,1]", "beta[10,1]"))

rescue_stan <- as.matrix(ml_stan, pars = list("beta[1,2]", "beta[2,2]", "beta[3,2]", "beta[4,2]", "beta[5,2]",
      "beta[6,2]", "beta[7,2]", "beta[8,2]", "beta[9,2]", "beta[10,2]"))  

tdies_stan <- as.matrix(ml_stan, pars = list("beta[1,3]", "beta[2,3]", "beta[3,3]", "beta[4,3]", "beta[5,3]",
      "beta[6,3]", "beta[7,3]", "beta[8,3]", "beta[9,3]", "beta[10,3]"))

tdominates_stan <- as.matrix(ml_stan, pars = list("beta[1,4]", "beta[2,4]", "beta[3,4]", "beta[4,4]", "beta[5,4]",
      "beta[6,4]", "beta[7,4]", "beta[8,4]", "beta[9,4]", "beta[10,4]"))   


p1 <- mcmc_intervals(slives_stan) + scale_y_discrete(labels = c("L", "N", "X",
      "kCO2", "astar", "kNPQ", "jSGm", "jCPm", "kROS", "b")) +
      ggtitle("Sensitive symb. allows host survival") + xlab("Slope of contribution to probability (softmax scale)")

p2 <- mcmc_intervals(rescue_stan) + scale_y_discrete(labels = c("L", "N", "X",
      "kCO2", "astar", "kNPQ", "jSGm", "jCPm", "kROS", "b")) +
      ggtitle("RESCUE") + xlab("Slope of contribution to probability (softmax scale)")

p3 <- mcmc_intervals(tdies_stan) + scale_y_discrete(labels = c("L", "N", "X",
      "kCO2", "astar", "kNPQ", "jSGm", "jCPm", "kROS", "b")) +
      ggtitle("Neither symb. allows host survival") + xlab("Slope of contribution to probability (softmax scale)")

p4 <- mcmc_intervals(tdominates_stan) + scale_y_discrete(labels = c("L", "N", "X",
      "kCO2", "astar", "kNPQ", "jSGm", "jCPm", "kROS", "b")) +
      ggtitle("Tolerant symb. alone allows survival; takes over") + xlab("Slope of contribution to probability (softmax scale)")

grid.arrange(p1, p2, p3, p4, nrow=2)
```
