---
title: "How much tolerant symbiont is required for survival?"
author: "A.L. Brown. F. Pfab, E.C. Baxter, A.R. Detmer, H.V. Moeller, R.M. Nisbet, and R. Cunning"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
      html_document:
            code_folding: hide
---

```{r set-options}
  # Set kintr options
  knitr::opts_chunk$set(echo = TRUE, cache = FALSE, fig.width=8, fig.height=8, results='hold')

  # Load packages
  library("coRal")
  library("foreach")
  library("parallel")
  library("doParallel")
  library("MASS")
  library("knitr")
  library("plot.matrix")

  # Plot size for running this in-line
  options(repr.plot.res=240)

  # Load functions
  source("R_functions/synth.R") # synthesizing unit (used in run_coral_competitive exclusion)
  source("R_functions/cn_limitation.R") # calculates carbon/nitrogen limitation of host and symbiont growth SUs
  source("R_functions/run_coral_competitive_exclusion.R") # run_coral that stops when symbiont 2 has declined to a certain fraction of symbiont 1
  source("R_functions/plotting_functions.R") # some custom plotting functions

  # Define colors
  colSen <- "#648FFF"
  colTol <- "#FFB000"
  colNS <- "#000000"
  colEither <- "#00FABE"
  colRescue <- "#DC267F"

  # Define plotting symbols
  pchSen <- 1
  pchTol <- 19
  pchNS <- 0
  pchEither <- 3
  pchRescue <- 15
```

```{r set-pars, cache=TRUE}
  #### Set parameters ####

  # Host and symbiont parameters
  pars <- def_pars(nsym=2)
  pars$jCPm[2] <- 1.0
  pars$kROS[2] <- 250
  pars$jSGm[2] <- 0.15

  # Tolerant symbiont amounts to investigate (as fraction of total symbiont population)
  tolAmounts <- c(0, 0.01, 0.1, 0.5, 0.9, 0.99, 1)

  # Randomly draw the environmental parameters
  env_params <- data.frame("L"=runif(10000, 5, 60), # Light, choose values between 5 and 60 mol photons/m^2/d
    "N"=runif(10000, 1e-8, 1e-5), # DIN, choose values between 1e-8 and 1e-5 mol/L
    "X" = runif(10000, 0, 4e-7)) # Food, choose values between 0 and 4e-7 mol/L
```


```{r run-sims, cache=TRUE, dependson=c("set-pars")}

  # Run simulations for 100 days
  time<-seq(0, 100, 0.1)

  # Set up to run simulations in parallel
  cl <- makeCluster(detectCores() - 1)
  registerDoParallel(cl)


  # results will temporarily hold the summary statistics from the simulations
  results <- foreach(i=1:nrow(env_params), .combine='rbind', .packages='dplyr') %dopar% {

    # Set up the environmental conditions
    env <- coRal::init_env(time=time, L=c(env_params[i, "L"], env_params[i, "L"], 0),
      N=c(env_params[i, "N"], env_params[i, "N"], 0), X=c(env_params[i, "X"], env_params[i, "X"], 0))

    # Check host survival for each tolerant amount
    survival <- list("L"=env_params[i, "L"], "N"=env_params[i, "N"], "X"=env_params[i, "X"])
    for (i in 1:length(tolAmounts)) {
      # Run the simulation
      pars_tmp <- pars
      pars_tmp$initS <- c(1 - tolAmounts[i], tolAmounts[i])
      run <- coRal::run_coral(time=time, env=env, pars=pars_tmp)

      # Check whether all parties are NOT carbon-limited
      cnlim <- cn_limitation(run, pars_tmp)
      noClimAll <- ((cnlim$H[length(time)] >= 0) & (cnlim$S.1[length(time)] >= 0) & (cnlim$S.2[length(time)] >= 0))

      # Check whether host growth is positive
      posGrH <- (run$dH.Hdt[length(time)] > 0)
      print(posGrH)

      # Record the result
      survival[[paste0("tol_", tolAmounts[i])]] <- (posGrH) #& noClimAll)
    }

    # Return the environmental parameters and survival information
    survival
  }

  # Stop the cluster
  stopCluster(cl)

  # Store results in dataframe, set column types
  sim_ts_reqd <- data.frame(results, row.names=NULL)
```

```{r reformat-sim-dataframe, cache=TRUE, depends=c("run-sims")}

  for (name in names(sim_ts_reqd)) { if (startsWith(name, "tol_")) { sim_ts_reqd[,name] <- as.logical(sim_ts_reqd[,name]) }}
  sim_ts_reqd$L <- as.numeric(sim_ts_reqd$L)
  sim_ts_reqd$N <- as.numeric(sim_ts_reqd$N)
  sim_ts_reqd$X <- as.numeric(sim_ts_reqd$X)
```

```{r results-matrices, cache=TRUE, depends=c("run-sims")}

  # Divisions on the x-axis of plots
  lightBreaks <- seq(5, 60, 2.5)
  nitrogenBreaks <- c(1e-8, seq(5e-7, 1e-5, 5e-7))
  foodBreaks <- seq(0, 4e-7, 2e-8)

  # Matrices that will hold results
  lightMat <- matrix(NA, nrow=length(tolAmounts), ncol=(length(lightBreaks) - 1))
  nitrogenMat <- matrix(NA, nrow=length(tolAmounts), ncol=(length(nitrogenBreaks) - 1))
  foodMat <- matrix(NA, nrow=length(tolAmounts), ncol=(length(foodBreaks) - 1))

  # Rows correspond to initial amount of tolerant symbiont as % of total symbiont population
  rownames(lightMat) <- rownames(nitrogenMat) <- rownames(foodMat) <- (tolAmounts*100)

  # Columns correspond to environmental variables
  colnames(lightMat) <- paste(lightBreaks[-length(lightBreaks)], lightBreaks[-1], sep="-")
  colnames(nitrogenMat) <- paste(nitrogenBreaks[-length(nitrogenBreaks)], nitrogenBreaks[-1], sep="-")
  colnames(foodMat) <- paste(foodBreaks[-length(foodBreaks)], foodBreaks[-1], sep="-")

  matList <- list("L"=lightMat, "N"=nitrogenMat, "X"=foodMat)
  breaksList <- list("L"=lightBreaks, "N"=nitrogenBreaks, "X"=foodBreaks)
  envVarList <- list("L", "N", "X")

  # Loop over the environmental variables (light, nitrogen, food)
  for (var in envVarList) {
    # Loop over the amount of tolerant symbionts
    for(i in 1:length(tolAmounts)) {
      # Loop over the "bins" of environmental variable values
      for (j in 1:(length(breaksList[[var]])-1)) {
        nSim <- sum((sim_ts_reqd[, var] > breaksList[[var]][j]) & (sim_ts_reqd[, var] <= breaksList[[var]][j + 1])) # number of simulations in the parameter range
        nSurvival <- sum(sim_ts_reqd[, paste0("tol_", tolAmounts[i])] & # survival
          (sim_ts_reqd[, var] > breaksList[[var]][j]) & (sim_ts_reqd[, var] <= breaksList[[var]][j + 1])) # in that parameter range

        # Also check the left boundary for the leftmost bin
        if (j == 1) {
          nSim <- nSim + sum(sim_ts_reqd[, var] == breaksList[[var]][j])
          nSurvival <- nSurvival +  sum(sim_ts_reqd[, paste0("tol_", tolAmounts[i])] & (sim_ts_reqd[, var] == breaksList[[var]][j]))
        }

        # Store the fraction of simulations the host survived
        matList[[var]][[i, j]] <- nSurvival/nSim
      }
    }
  }

  lightMat <- matList$L
  nitrogenMat <- matList$N
  foodMat <- matList$X
```


```{r plot-results-heatmap, cache=TRUE, depends=c("run-sims"), fig.height=15, fig.width=15}
  pdf("ST_ratio_survival_light.pdf", 15, 7.5)
  layout(matrix(c(1, 2), nrow=1), width=c(5, 1))

  # Plot survival (color), x=light, y=% tolerant
  plot(lightMat[nrow(lightMat):1,]*100, breaks=c(0, 1/(nrow(sim_ts_reqd) + 1), seq(0.2, 0.8, 0.2), 1 - (1/(nrow(sim_ts_reqd) + 1)), 1)*100,
    col=hcl.colors(8, pal="Blues"), xlab="Light (mol photons/m^2/day)", ylab="Initial % tolerant symbionts",
    main="Effect of amount of tolerant symbiont on host survival\nvs light", asp=TRUE, border=NA, key=NULL)

  # Legend
  par(mar=c(0, 0, 0, 0))
  plot.new()
  legend("center", c("No cases", "0-20%", "20-40%", "40-60%", "60-80%", "80-100%", "All cases"), col=hcl.colors(8, pal="Blues"),
    pch=15, title="% of simulations\nwhere host survives", bty="n")

  dev.off()

  pdf("ST_ratio_survival_nitrogen.pdf", 15, 7.5)
  layout(matrix(c(1, 2), nrow=1), width=c(5, 1))

  # Plot survival (color), x=nitrogen, y=% tolerant
  plot(nitrogenMat[nrow(nitrogenMat):1,], breaks=c(0, 1/(nrow(sim_ts_reqd) + 1), seq(0.2, 0.8, 0.2), 1 - (1/(nrow(sim_ts_reqd) + 1)), 1),
    col=hcl.colors(8, pal="Blues"), xlab="Nitrogen (mol/L)", ylab="Initial % tolerant symbionts",
    main="Effect of amount of tolerant symbiont on host survival\nvs nitrogen", asp=TRUE, border=NA, key=NULL)

  # Legend
  par(mar=c(0, 0, 0, 0))
  plot.new()
  legend("center", c("No cases", "0-20%", "20-40%", "40-60%", "60-80%", "80-100%", "All cases"), col=hcl.colors(8, pal="Blues"),
    pch=15, title="% of simulations\nwhere host survives", bty="n")

  dev.off()

  pdf("ST_ratio_survival_prey.pdf", 15, 7.5)
  layout(matrix(c(1, 2), nrow=1), width=c(5, 1))

  # Plot survival (color), x=prey, y=% tolerant
  plot(foodMat[nrow(foodMat):1,], breaks=c(0, 1/(nrow(sim_ts_reqd) + 1), seq(0.2, 0.8, 0.2), 1 - (1/(nrow(sim_ts_reqd) + 1)), 1),
    col=hcl.colors(8, pal="Blues"), xlab="Prey (mol/L)", ylab="Initial % tolerant symbionts",
    main="Effect of amount of tolerant symbiont on host survival\nvs prey", asp=TRUE, border=NA, key=NULL)

  # Legend
  par(mar=c(0, 0, 0, 0))
  plot.new()
  legend("center", c("No cases", "0-20%", "20-40%", "40-60%", "60-80%", "80-100%", "All cases"), col=hcl.colors(8, pal="Blues"),
    pch=15, title="% of simulations\nwhere host survives", bty="n")

  dev.off()
```


```{r plot-sample-sims, cache=TRUE, depends=c("run-sims")}
    ##### Some sample plots of hosts that survive with sensitive but not tolerant symbionts

    time <- seq(0, 365, 0.1)
    pars_sen <- def_pars()
    pars_tol <- def_pars()
    pars_tol$jCPm <- 1.0
    pars_tol$kROS <- 250
    pars_tol$jSGm <- 0.15


    env <- init_env(time, L=c(5, 5, 0),
    	N=c(5e-6, 5e-6, 0),
    	X=c(0, 0, 0))

    run_sen <- run_coral(time, env, pars_sen)
    run_tol <- run_coral(time, env, pars_tol)

    plot(time, run_sen$dH.Hdt)
    plot(time, run_tol$dH.Hdt)

    pdf("Low_light_survives_with_S_not_T.pdf")
    par(mfrow=c(2, 1))
    plot(time, run_sen$jCP, type="l", col="blue", ylim=c(0, 0.75),
    	main="Host survives with S. but not T. symb.\nL=5 mol photons/m^2/day, N=5e-6 mol/L, X=0 mol/L\nPhotosynthetic rate (jCP)",
    	xlab="Time (days)", ylab="jCP")
    lines(time, run_tol$jCP, col="orange", lwd=2)

    plot(time, run_sen$rhoC/run_sen$H * run_sen$S, col="blue", type="l", ylim=c(0, 0.75),
    	main="Carbon shared per unit host biomass", xlab="Time (days)", ylab="rhoC * S/H")
    lines(time, run_tol$rhoC/run_tol$H * run_tol$S, col="orange", lwd=2)

    legend("topright", c("Sensitive symb.", "Tolerant symb."),
    	col=c("blue", "orange"), lwd=c(1, 2))
    dev.off()




    env <- init_env(time, L=c(30, 30, 0),
    	N=c(5e-6, 5e-6, 0),
    	X=c(0, 0, 0))

    run_sen <- run_coral(time, env, pars_sen)
    run_tol <- run_coral(time, env, pars_tol)

    plot(time, run_sen$dH.Hdt)
    plot(time, run_tol$dH.Hdt)

    pdf("Intermediate_light_survives_with_S_not_T.pdf")
    par(mfrow=c(2, 1))
    plot(time, run_sen$jCP, type="l", col="blue", ylim=c(0, 2),
    	main="Host survives with S. but not T. symb.\nL=30 mol photons/m^2/day, N=5e-6 mol/L, X=0 mol/L\nPhotosynthetic rate (jCP)",
    	xlab="Time (days)", ylab="jCP")
    lines(time, run_tol$jCP, col="orange", lwd=2)

    plot(time, run_sen$rhoC/run_sen$H * run_sen$S, col="blue", type="l", ylim=c(0, 2),
    	main="Carbon shared per unit host biomass", xlab="Time (days)", ylab="rhoC * S/H")
    lines(time, run_tol$rhoC/run_tol$H * run_tol$S, col="orange", lwd=2)

    legend("topright", c("Sensitive symb.", "Tolerant symb."),
    	col=c("blue", "orange"), lwd=c(1, 2))
    dev.off()
```
